### ISSUE TITLE
pylint assets.py

### ISSUE THREAD

**Issue by yuritaba** [yuritaba/pygame_opendev#1]
************* Module assets
src/assets.py:4:74: C0303: Trailing whitespace (trailing-whitespace)
src/assets.py:12:0: C0301: Line too long (205/100) (line-too-long)
src/assets.py:49:0: C0301: Line too long (101/100) (line-too-long)
src/assets.py:70:0: C0301: Line too long (104/100) (line-too-long)
src/assets.py:72:0: C0301: Line too long (106/100) (line-too-long)
src/assets.py:73:0: C0301: Line too long (102/100) (line-too-long)
src/assets.py:93:0: C0303: Trailing whitespace (trailing-whitespace)
src/assets.py:122:0: C0303: Trailing whitespace (trailing-whitespace)
src/assets.py:43:0: C0116: Missing function or method docstring (missing-function-docstring)
src/assets.py:43:0: R0915: Too many statements (62/50) (too-many-statements)

**Comment by rafaelgpaves** [comment]
Estou trabalhando nesse
